# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PC Controller' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PC Controller

  target 'PC ControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PC ControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'CocoaAsyncSocket'
  pod 'Masonry'
  pod 'SVProgressHUD'
end
